#!/usr/bin/env python3
"""Generate `docs/RECORDED-RUN.md` from an actual run.

The recorded run is a deliverable, and a deliverable that is pasted by hand
drifts from the code the first time anything changes. So it is generated:

    python scripts/record_run.py

Everything in the output comes from the harness. The preamble is the only prose
this script contributes, and it says so.

Pass `--scripted` to record against the scripted model client instead of the
API, which is what happens when no key is configured.
"""
from __future__ import annotations

import argparse
import io
import shutil
import sys
from contextlib import redirect_stdout
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests"))

import console  # noqa: E402
from harness.kernel import Harness  # noqa: E402
from harness.plan.llm import DEFAULT_MODEL, build_client  # noqa: E402

PREAMBLE = """\
# A recorded run

Scenario A end to end: the unprompted detection, the approval prompt the manager
sees, the backup routing when they do not answer, the execution as a declared
workflow, the follow-up, and the audit trail reconstructed from the log alone.

Generated by `python scripts/record_run.py`. Every line below this preamble is
harness output. Nothing is pasted or edited.

- **Model**: {mode}
- **Clock starts at**: 2026-09-02T09:00, a Wednesday
- **Subject**: Dana Whitfield, Purchasing Manager, `u-101`

"""

TRAILER = """
---

## What to look for

**The alert is the brief's sentence.** The headline states the risk, names the
cause, proposes the action, and asks. Every factual claim in it is tied to a
record id in `citations`, so a reader can check it against the ERP rather than
trusting it.

**The gate ran four rules and named all four.** Including the ones that passed.
A refusal that says only "denied" is not something a person can act on.

**The approval moved without anybody deciding it should.** Dana did not answer
by 17:00 and her calendar shows her out the next day, so the request went to her
designated backup, and her later attempt to approve it was refused. Authority
did not travel with the request: Marcus was re-checked against his own limit.

**The model chose between two suppliers, not five.** `candidates_offered` shows
what it was given. Apex Rapid Components is approved, quotes the lowest price on
file for this part, ships next day, and emailed an offer that morning. It is not
approved for *this part*, so code removed it before the model saw the list, and
step two re-derives approval from the supplier record anyway.

**The audit answers all five questions.** What the agent saw is in
`context.gathered`, including the provider it was not allowed to use. What it
concluded is in `plan.produced`, with the size of the context window that
produced it. What it was allowed to do is in `gate.allowed`, rule by rule. Who
approved is in `approval.approved`, with the routing that got it there. What
happened in each system is in the `tool.invoked` entries, each with its
idempotency key.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--scripted", action="store_true")
    parser.add_argument("--out", default=str(ROOT / "docs" / "RECORDED-RUN.md"))
    args = parser.parse_args()

    if args.scripted:
        import stub_llm

        llm = stub_llm.combined()
        mode = "scripted client (no API key configured)"
    else:
        llm = build_client(ROOT / "cassettes")
        mode = f"`{DEFAULT_MODEL}` via the Claude API, recorded to `cassettes/` and replayable"

    workdir = ROOT / "_record"
    shutil.rmtree(workdir, ignore_errors=True)
    workdir.mkdir(parents=True)

    harness = Harness(
        db_path=workdir / "harmony.db",
        company_dir=ROOT / "company",
        runs_dir=workdir / "runs",
        cassette_dir=ROOT / "cassettes",
        llm=llm,
    )
    harness.initialise()

    buffer = io.StringIO()
    try:
        with redirect_stdout(buffer):
            import demo

            state = demo.scenario_a(harness)
            demo.follow_up(harness, state)
            demo.audit_trail(harness, state)
    finally:
        harness.close()

    body = buffer.getvalue()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        PREAMBLE.format(mode=mode) + "```\n" + body.strip("\n") + "\n```\n" + TRAILER,
        encoding="utf-8",
    )
    shutil.rmtree(workdir, ignore_errors=True)
    print(f"wrote {out} ({len(body.splitlines())} lines of harness output)")
    return 0


if __name__ == "__main__":
    # Colour off: this is a file, not a terminal.
    console.configure()
    raise SystemExit(main())
